In [2]:
import torch
import numpy as np

In [6]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [10]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [13]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7956, 0.1279],
        [0.7863, 0.1459]]) 



In [17]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape, dtype=int)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1293, 0.6410, 0.6133],
        [0.4624, 0.3222, 0.1067]]) 

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0, 0],
        [0, 0, 0]])


In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

==>> tensor:  tensor([[0.1680, 0.4661, 0.7295, 0.3192],
        [0.3525, 0.8895, 0.8888, 0.4133],
        [0.8745, 0.2803, 0.8812, 0.0018]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
